Repository Team-Omechu/Omechu-web, pull requests merged in 2025-08, with the labels that each got.

#133 main으로 중간 배포
  omechu-app/next.config.ts
  omechu-app/src/app/(auth)/sign-in/components/SignInForm.tsx
  omechu-app/src/app/(auth)/sign-up/page.tsx
  omechu-app/src/app/components/common/FoodCard.tsx
  omechu-app/src/app/components/common/LoadingIndicator.tsx
  omechu-app/src/app/components/common/SkeletonFoodCard.tsx
  omechu-app/src/app/components/common/SkeletonRestaurantReviewCard.tsx
  omechu-app/src/app/constant/terms/locationInfo.ts
  omechu-app/src/app/globals.css
  omechu-app/src/app/layout.tsx
  omechu-app/src/app/lib/api/auth.ts
  omechu-app/src/app/lib/api/axios.ts
  omechu-app/src/app/lib/stores/auth.store.ts
  omechu-app/src/app/mainpage/example_testpage/components/LoginPromptModal2.tsx
  omechu-app/src/app/mypage/AuthErrorModalSection.tsx
  omechu-app/src/app/mypage/MenuSection.tsx
  omechu-app/src/app/mypage/ProfileSection.tsx
  omechu-app/src/app/mypage/api/favorites.ts
  omechu-app/src/app/mypage/api/myActivity.ts
  omechu-app/src/app/mypage/api/profile.ts
  omechu-app/src/app/mypage/api/updateProfile.ts
  omechu-app/src/app/mypage/favorites/FavoritesSection.tsx
  omechu-app/src/app/mypage/favorites/page.tsx
  omechu-app/src/app/mypage/hooks/useProfile.ts
  omechu-app/src/app/mypage/hooks/useProfileQuery.ts
  omechu-app/src/app/mypage/my-activity/page.tsx
  omechu-app/src/app/mypage/page.tsx
  omechu-app/src/app/mypage/profile-edit/NicknameInput.tsx
  omechu-app/src/app/mypage/profile-edit/ProfileEditSection.tsx
  omechu-app/src/app/mypage/profile-edit/ProfileImageUploader.tsx
  omechu-app/src/app/mypage/profile-edit/page.tsx
  omechu-app/src/app/mypage/settings/SettingsClient.tsx
  omechu-app/src/app/mypage/settings/account-settings/AccountSettingsClient.tsx
  omechu-app/src/app/mypage/settings/account-settings/change-password/ChangePasswordClient.tsx
  omechu-app/src/app/mypage/settings/account-settings/change-password/page.tsx
  omechu-app/src/app/mypage/settings/account-settings/page.tsx
  omechu-app/src/app/mypage/settings/page.tsx
  omechu-app/src/app/mypage/settings/terms/location-info/page.tsx
  omechu-app/src/app/mypage/settings/terms/page.tsx
  omechu-app/src/app/mypage/settings/terms/personal-info/page.tsx
  omechu-app/src/app/mypage/settings/terms/service/page.tsx
  omechu-app/src/app/mypage/types/MyPlaceApiResponseType.ts
  omechu-app/src/app/mypage/types/profileType.ts
  omechu-app/src/app/mypage/user-info-edit/[step]/AllergyStep.tsx
  omechu-app/src/app/mypage/user-info-edit/page.tsx
  omechu-app/src/app/onboarding/[step]/page.tsx
Labels: test

#135 Feature/mainpage api2 #117
  omechu-app/next.config.ts
  omechu-app/src/app/components/common/MenuInfoCard.tsx
  omechu-app/src/app/constant/mainpage/RestaurantData.ts
  omechu-app/src/app/constant/mainpage/mukburim.ts
  omechu-app/src/app/constant/mainpage/profile.ts
  omechu-app/src/app/lib/stores/tagData.store.ts
  omechu-app/src/app/mainpage/api/api.ts
  omechu-app/src/app/mainpage/components/BudgetStep.tsx
  omechu-app/src/app/mainpage/components/FoodCardEx.tsx
  omechu-app/src/app/mainpage/components/MealTimeStep.tsx
  omechu-app/src/app/mainpage/components/MoodStep.tsx
  omechu-app/src/app/mainpage/components/PurposeStep.tsx
  omechu-app/src/app/mainpage/components/RandomRecommendModal.tsx
  omechu-app/src/app/mainpage/components/TagCard.tsx
  omechu-app/src/app/mainpage/components/WhoStep.tsx
  omechu-app/src/app/mainpage/example_testpage/components/LoginPromptModal.tsx
  omechu-app/src/app/mainpage/hooks/useGetProfile.ts
  omechu-app/src/app/mainpage/hooks/useHeart.ts
  omechu-app/src/app/mainpage/hooks/usePostMukburim.ts
  omechu-app/src/app/mainpage/page.tsx
  omechu-app/src/app/mainpage/random-recommend/page.tsx
  omechu-app/src/app/mainpage/result/[menuId]/page.tsx
  omechu-app/src/app/mainpage/result/page.tsx
Labels: feat, style, refactor

#145 [Feat] 먹부림 기록 페이지까지 배포 최신화
  omechu-app/package.json
  omechu-app/src/app/components/common/CustomDatePicker.tsx
  omechu-app/src/app/components/common/FoodBox.tsx
  omechu-app/src/app/components/common/SkeletonUIFoodBox.tsx
  omechu-app/src/app/layout.tsx
  omechu-app/src/app/mypage/MenuSection.tsx
  omechu-app/src/app/mypage/ProfileSection.tsx
  omechu-app/src/app/mypage/api/mukburim.ts
  omechu-app/src/app/mypage/api/recommend.ts
  omechu-app/src/app/mypage/foodie-log/FoodieLogClient.tsx
  omechu-app/src/app/mypage/foodie-log/page.tsx
  omechu-app/src/app/mypage/page.tsx
  omechu-app/src/app/mypage/recommended-list/RecommendedListClient.tsx
  omechu-app/src/app/mypage/user-info-edit/page.tsx
  omechu-app/yarn.lock
Labels: feat

#144 Feature/mainpage api2 #117
  omechu-app/src/app/components/common/MenuInfoCard.tsx
  omechu-app/src/app/components/mainpage/MainLoading.tsx
  omechu-app/src/app/constant/mainpage/likeList.ts
  omechu-app/src/app/constant/mainpage/resultData.ts
  omechu-app/src/app/fullmenu/components/FoodListSection.tsx
  omechu-app/src/app/fullmenu/menu-detail/page.tsx
  omechu-app/src/app/fullmenu/menu-detail/recipe-detail/page.tsx
  omechu-app/src/app/fullmenu/page.tsx
  omechu-app/src/app/lib/stores/locationAnswer.store.ts
  omechu-app/src/app/lib/stores/questionAnswer.store.ts
  omechu-app/src/app/mainpage/api/api.ts
  omechu-app/src/app/mainpage/components/FinalChoiceStep.tsx
  omechu-app/src/app/mainpage/components/FoodCardEx.tsx
  omechu-app/src/app/mainpage/components/RandomRecommendModal.tsx
  omechu-app/src/app/mainpage/hooks/useGetMenuDetail.ts
  omechu-app/src/app/mainpage/hooks/useGetRandomMenu.ts
  omechu-app/src/app/mainpage/hooks/useHeart.ts
  omechu-app/src/app/mainpage/hooks/usePostMukburim.ts
  omechu-app/src/app/mainpage/location-answer/page.tsx
  omechu-app/src/app/mainpage/meal-answer/page.tsx
  omechu-app/src/app/mainpage/page.tsx
  omechu-app/src/app/mainpage/random-recommend/page.tsx
  omechu-app/src/app/mainpage/result/[menuId]/page.tsx
  omechu-app/src/app/mainpage/result/page.tsx
  omechu-app/src/app/restaurant/restaurant-detail/[id]/map/components/KakaoMap.tsx
  omechu-app/src/app/restaurant/restaurant-detail/[id]/map/components/RestaurantMapPreview.tsx
  omechu-app/src/app/restaurant/restaurant-detail/[id]/map/page.tsx
Labels: feat, style, refactor

#150 Feat/맛집 페이지 관련
  omechu-app/src/app/components/common/FoodCard.tsx
  omechu-app/src/app/constant/RegionList.ts
  omechu-app/src/app/restaurant/api/restaurantList.ts
  omechu-app/src/app/restaurant/api/restaurantSearch.ts
  omechu-app/src/app/restaurant/components/FoodCardList.tsx
  omechu-app/src/app/restaurant/components/RestaurantPage.tsx
  omechu-app/src/app/restaurant/restaurant-detail/[id]/components/ReviewList/Review.tsx
Labels: feat

#149 Feat/기본상태입력 api 연동#146
  omechu-app/src/app/constant/mypage/profileOptions.ts
  omechu-app/src/app/mypage/api/updateProfile.ts
  omechu-app/src/app/mypage/mappers/profilePayload.ts
  omechu-app/src/app/mypage/profile-edit/ProfileEditSection.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/AllergyStep.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/FoodStep.tsx
Labels: feat, fix, hotfix

#151 Feat/메뉴 관련 페이지 api 연동
  omechu-app/src/app/components/common/FoodBox.tsx
  omechu-app/src/app/components/common/MenuInfoCard.tsx
  omechu-app/src/app/constant/mainpage/resultData.ts
  omechu-app/src/app/fullmenu/api/menu.ts
  omechu-app/src/app/fullmenu/components/FoodListSection.tsx
  omechu-app/src/app/fullmenu/components/FullMenuClient.tsx
  omechu-app/src/app/fullmenu/hooks/useMenuQueries.ts
  omechu-app/src/app/fullmenu/menu-detail/page.tsx
  omechu-app/src/app/fullmenu/menu-detail/recipe-detail/page.tsx
  omechu-app/src/app/fullmenu/page.tsx
  omechu-app/src/app/lib/types/menu.ts
  omechu-app/src/app/lib/types/restaurant.ts
  omechu-app/src/app/mainpage/api/api.ts
  omechu-app/src/app/mainpage/components/RandomRecommendModal.tsx
  omechu-app/src/app/mainpage/hooks/useGetMenuDetail.ts
  omechu-app/src/app/mainpage/result/[menuId]/page.tsx
  omechu-app/src/app/restaurant/api/restaurantList.ts
  omechu-app/src/app/restaurant/api/restaurantSearch.ts
  omechu-app/src/app/restaurant/restaurant-detail/[id]/page.tsx
Labels: feat

#172 [Fix] mypage 버그 수정 후 main으로 최신화 배포
  omechu-app/src/app/(auth)/sign-in/components/SignInForm.tsx
  omechu-app/src/app/ClientLayout.tsx
  omechu-app/src/app/components/common/Bottom.tsx
  omechu-app/src/app/constant/UserInfoEditSteps.ts
  omechu-app/src/app/lib/api/auth.ts
  omechu-app/src/app/lib/api/axios.ts
  omechu-app/src/app/lib/stores/onboarding.store.ts
  omechu-app/src/app/mypage/AuthErrorModalSection.tsx
  omechu-app/src/app/mypage/ProfileSection.tsx
  omechu-app/src/app/mypage/api/profile.ts
  omechu-app/src/app/mypage/api/updateProfile.ts
  omechu-app/src/app/mypage/favorites/FavoritesSection.tsx
  omechu-app/src/app/mypage/hooks/useProfileQuery.ts
  omechu-app/src/app/mypage/mappers/profilePayload.ts
  omechu-app/src/app/mypage/my-activity/MyActivityClient.tsx
  omechu-app/src/app/mypage/recommended-list/RecommendedListClient.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/AllergyStep.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/ConditionStep.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/FoodStep.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/GenderStep.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/StateStep.tsx
  omechu-app/src/app/mypage/user-info-edit/page.tsx
  omechu-app/tailwind.config.js
Labels: feat, fix, design, hotfix

#177 [FIX] Mypage QA 2차 반영 #173
  omechu-app/src/app/(auth)/sign-in/components/SignInForm.tsx
  omechu-app/src/app/ClientLayout.tsx
  omechu-app/src/app/auth/reset-password/page.tsx
  omechu-app/src/app/components/common/FoodCard.tsx
  omechu-app/src/app/components/common/Header.tsx
  omechu-app/src/app/components/common/ModalWrapper.tsx
  omechu-app/src/app/components/common/RestaurantReviewCard.tsx
  omechu-app/src/app/components/common/SkeletonFoodCard.tsx
  omechu-app/src/app/components/common/SkeletonRestaurantReviewCard.tsx
  omechu-app/src/app/lib/stores/auth.store.ts
  omechu-app/src/app/mypage/ProfileSection.tsx
  omechu-app/src/app/mypage/api/myActivity.ts
  omechu-app/src/app/mypage/api/updateRestaurant.ts
  omechu-app/src/app/mypage/favorites/FavoritesSection.tsx
  omechu-app/src/app/mypage/my-activity/MyActivityClient.tsx
  omechu-app/src/app/mypage/page.tsx
  omechu-app/src/app/mypage/profile-edit/ProfileEditSection.tsx
  omechu-app/src/app/mypage/profile-edit/page.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/ConditionStep.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/FoodStep.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/GenderStep.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/StateStep.tsx
  omechu-app/src/app/restaurant/components/RestaurantAddModal/RestaurantEditModal.tsx
Labels: feat, fix, design, remove, hotfix

#181 The Journey to demoDay
  omechu-app/src/app/mypage/user-info-edit/[step]/AllergyStep.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/ConditionStep.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/FoodStep.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/GenderStep.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/StateStep.tsx
  omechu-app/src/app/mypage/user-info-edit/utils/resetBasicState.ts
Labels: fix, hotfix

#175 [FIX] restaurant qa 1차
  omechu-app/src/app/components/common/FoodCard.tsx
  omechu-app/src/app/lib/types/restaurant.ts
  omechu-app/src/app/restaurant/api/restaurantList.ts
  omechu-app/src/app/restaurant/components/FoodCardList.tsx
  omechu-app/src/app/restaurant/restaurant-detail/[id]/map/page.tsx
  omechu-app/src/app/restaurant/restaurant-detail/[id]/page.tsx
Labels: fix

#191 The Journey to the demoDay
  omechu-app/src/app/lib/stores/onboarding.store.ts
  omechu-app/src/app/mypage/api/favorites.ts
  omechu-app/src/app/mypage/api/myActivity.ts
  omechu-app/src/app/mypage/my-activity/MyActivityClient.tsx
Labels: fix, hotfix
