Repository Team-Omechu/Omechu-web, pull requests merged in 2025-07, with the labels that each got.

#6 Refactor/layout bottomnav conditional
  omechu-app/public/camera_Icon.png
  omechu-app/public/profile.png
  omechu-app/public/right_arrow.png
  omechu-app/public/right_arrow.svg
  omechu-app/public/setting.png
  omechu-app/public/x_icon.png
  omechu-app/src/app/ClientLayout.tsx
  omechu-app/src/app/components/common/Header.tsx
  omechu-app/src/app/layout.tsx
  omechu-app/src/app/mypage/page.tsx
  omechu-app/src/app/mypage/profile-edit/page.tsx
  omechu-app/src/app/mypage/user-info-edit/page.tsx
  omechu-app/src/app/mypage/user-info-setup/gender/page.tsx
  omechu-app/src/app/mypage/user-info-setup/page.tsx
Labels: bug

#26 feat: full menu UI #15
  omechu-app/public/customselect.png
  omechu-app/src/app/components/common/Bottom.tsx
  omechu-app/src/app/components/common/SearchBar.tsx
  omechu-app/src/app/components/common/Tag.tsx
  omechu-app/src/app/components/fullmenu/FilterModal.tsx
  omechu-app/src/app/fullmenu/page.tsx
  omechu-app/src/app/mypage/recommended-list/page.tsx
Labels: feat, design

#34 Feat/terms#31 마이페이지/이용약관 화면 및 기능 구현
  omechu-app/next.config.ts
  omechu-app/package-lock.json
  omechu-app/package.json
  omechu-app/public/right_arrow_black.png
  omechu-app/src/app/ClientLayout.tsx
  omechu-app/src/app/components/common/Header.tsx
  omechu-app/src/app/components/common/SearchBar.tsx
  omechu-app/src/app/constant/initialFoodList.ts
  omechu-app/src/app/constant/suggestionList.ts
  omechu-app/src/app/constant/terms/locationInfo.ts
  omechu-app/src/app/constant/terms/personlInfo.ts
  omechu-app/src/app/constant/terms/service.ts
  omechu-app/src/app/mypage/recommended-list/page.tsx
  omechu-app/src/app/mypage/terms/location-info/page.tsx
  omechu-app/src/app/mypage/terms/page.tsx
  omechu-app/src/app/mypage/terms/personal-info/page.tsx
  omechu-app/src/app/mypage/terms/service/page.tsx
  omechu-app/tailwind.config.js
  omechu-app/yarn.lock
Labels: feat, docs

#28 feat: auth UI #24
  omechu-app/package.json
  omechu-app/public/onboarding-restaurant-icon.png
  omechu-app/public/비밀번호보기.svg
  omechu-app/src/app/ClientLayout.tsx
  omechu-app/src/app/auth/signup/page.tsx
  omechu-app/src/app/components/auth/Button.tsx
  omechu-app/src/app/components/auth/LocationModal.tsx
  omechu-app/src/app/components/auth/PrivacyModal.tsx
  omechu-app/src/app/components/auth/TermsModal.tsx
  omechu-app/src/app/components/auth/TermsOfServiceModal.tsx
  omechu-app/src/app/components/onboarding/AllergyStep.tsx
  omechu-app/src/app/components/onboarding/ConstitutionStep.tsx
  omechu-app/src/app/components/onboarding/GenderStep.tsx
  omechu-app/src/app/components/onboarding/OnboardingButton.tsx
  omechu-app/src/app/components/onboarding/OnboardingStepLayout.tsx
  omechu-app/src/app/components/onboarding/PreferredFoodStep.tsx
  omechu-app/src/app/components/onboarding/ProfileStep.tsx
  omechu-app/src/app/components/onboarding/WorkoutStatusStep.tsx
  omechu-app/src/app/onboarding/[step]/page.tsx
  omechu-app/src/app/onboarding/gender/page.tsx
  omechu-app/src/app/onboarding/profile/page.tsx
  omechu-app/src/lib/schemas/auth.schema.ts
  omechu-app/src/lib/stores/onboarding.store.ts
  omechu-app/yarn.lock
Labels: feat, remove

#48 Design/components #47
  omechu-app/public/Home.png
  omechu-app/public/header_left_arrow.png
  omechu-app/public/left_arrow.png
  omechu-app/public/menu.png
  omechu-app/public/menu.svg
  omechu-app/public/mypage.png
  omechu-app/public/profile.png
  omechu-app/public/restaurant.png
  omechu-app/src/app/components/common/Bottom.tsx
  omechu-app/src/app/fullmenu/menu-detail/page.tsx
  omechu-app/src/app/fullmenu/menu-detail/recipe-detail/page.tsx
  omechu-app/src/app/mypage/page.tsx
  omechu-app/src/app/mypage/profile-edit/page.tsx
  omechu-app/src/app/mypage/recommended-list/page.tsx
  omechu-app/src/app/mypage/settings/account-settings/change-password/page.tsx
  omechu-app/src/app/mypage/settings/account-settings/page.tsx
  omechu-app/src/app/mypage/settings/page.tsx
  omechu-app/src/app/mypage/terms/location-info/page.tsx
  omechu-app/src/app/mypage/terms/page.tsx
  omechu-app/src/app/mypage/terms/personal-info/page.tsx
  omechu-app/src/app/mypage/terms/service/page.tsx
  omechu-app/src/app/mypage/user-info-edit/page.tsx
  omechu-app/src/app/mypage/user-info-setup/allergy/page.tsx
  omechu-app/src/app/mypage/user-info-setup/page.tsx
Labels: design

#56 Fix/build errors 해결
  .github/workflows/ci.yml
  omechu-app/src/app/fullmenu/menu-detail/page.tsx
  omechu-app/src/app/fullmenu/menu-detail/recipe-detail/page.tsx
  omechu-app/src/app/fullmenu/page.tsx
Labels: fix

#78 feature: Gemini Code Review 도입 #77
  .gemini/config.yaml
  .gemini/styleguide.md
Labels: feat, chore

#79 refactor: fullmenu, restaurant 관련 코드 리팩토링 #61
  omechu-app/src/app/ClientLayout.tsx
  omechu-app/src/app/components/common/FoodCard.tsx
  omechu-app/src/app/constant/restaurant/restaurantList.ts
  omechu-app/src/app/constant/restautantFoodList.ts
  omechu-app/src/app/restaurant/page.tsx
  omechu-app/src/app/restaurant/restaurant-detail/[id]/map/page.tsx
  omechu-app/src/app/restaurant/restaurant-detail/[id]/page.tsx
Labels: feat, refactor

#80 Feat/favorites#72
  omechu-app/public/arrow/arrow_down.png
  omechu-app/public/arrow/arrow_up.png
  omechu-app/public/arrow/header_left_arrow.png
  omechu-app/public/arrow/left-header-arrow.svg
  omechu-app/public/arrow/right_arrow.png
  omechu-app/public/arrow/right_arrow.svg
  omechu-app/public/arrow/right_arrow_black.png
  omechu-app/public/arrow/right_arrow_white.png
  omechu-app/public/components/common/eye_closed.svg
  omechu-app/public/components/common/eye_open.svg
  omechu-app/public/logo/logo.png
  omechu-app/public/logo/logo.svg
  omechu-app/public/profile/camera.svg
  omechu-app/public/profile/profile_default_img.svg
  omechu-app/public/profile/profile_default_img_rotated.svg
  omechu-app/public/x/cancel.svg
  omechu-app/public/x/close_button.png
  omechu-app/src/app/ClientLayout.tsx
  omechu-app/src/app/auth/forgot-password/page.tsx
  omechu-app/src/app/auth/sign-in/components/SignInForm.tsx
  omechu-app/src/app/components/common/FoodCard.tsx
  omechu-app/src/app/components/common/Input.tsx
  omechu-app/src/app/components/common/Toast.tsx
  omechu-app/src/app/components/restaurant/restaurantFoodList.ts
  omechu-app/src/app/constant/restaurant/restaurantList2.ts
  omechu-app/src/app/constant/restautantFoodList.ts
  omechu-app/src/app/mypage/favorites/page.tsx
  omechu-app/src/app/mypage/page.tsx
  omechu-app/src/app/mypage/profile-edit/page.tsx
  omechu-app/src/app/mypage/recommended-list/page.tsx
  omechu-app/src/app/mypage/settings/account-settings/change-password/page.tsx
  omechu-app/src/app/mypage/settings/account-settings/page.tsx
  omechu-app/src/app/mypage/settings/page.tsx
  omechu-app/src/app/mypage/settings/terms/location-info/page.tsx
  omechu-app/src/app/mypage/settings/terms/page.tsx
  omechu-app/src/app/mypage/settings/terms/personal-info/page.tsx
  omechu-app/src/app/mypage/settings/terms/service/page.tsx
  omechu-app/src/app/mypage/user-info-edit/[step]/EditStart.tsx
  omechu-app/src/app/mypage/user-info-edit/page.tsx
  omechu-app/src/app/page.tsx
  omechu-app/src/app/restaurant/restaurant-detail/[id]/map/page.tsx
  omechu-app/src/app/restaurant/restaurant-detail/[id]/page.tsx
Labels: feat, docs, design, refactor

#84 feature: Keyword.tsx 공용 컴포넌트 분리 및 맛집 후기 등록 UI #75
  omechu-app/package.json
  omechu-app/public/restaurant/camera-fill.svg
  omechu-app/src/app/components/common/Keyword.tsx
  omechu-app/src/app/components/restaurant/FilterSection/FilterTagList.tsx
  omechu-app/src/app/components/restaurant/KeywordSection/KeywordSelector.tsx
  omechu-app/src/app/components/restaurant/Review.tsx
  omechu-app/src/app/components/restaurant/restaurant-detail/RestaurantDetailHeader.tsx
  omechu-app/src/app/components/restaurant/restaurant-detail/RestaurantImageCarousel.tsx
  omechu-app/src/app/components/restaurant/restaurant-detail/RestaurantInfoBox.tsx
  omechu-app/src/app/components/restaurant/restaurant-detail/ReviewList.tsx
  omechu-app/src/app/components/restaurant/restaurant-detail/ReviewWriter.tsx
  omechu-app/src/app/components/restaurant/restaurant-detail/map/RestaurantMapPreview.tsx
  omechu-app/src/app/components/restaurant/restaurant-detail/modal/ImageUploader.tsx
  omechu-app/src/app/components/restaurant/restaurant-detail/modal/RatingSelector.tsx
  omechu-app/src/app/components/restaurant/restaurant-detail/modal/ReviewModal.tsx
  omechu-app/src/app/components/restaurant/restaurant-detail/modal/TagSelector.tsx
  omechu-app/src/app/components/restaurant/restaurant-detail/modal/TextReview.tsx
  omechu-app/src/app/constant/restaurant/restaurantList.ts
  omechu-app/src/app/mypage/favorites/page.tsx
  omechu-app/src/app/restaurant/restaurant-detail/[id]/map/page.tsx
  omechu-app/src/app/restaurant/restaurant-detail/[id]/page.tsx
  omechu-app/yarn.lock
Labels: feat, design, refactor

#99 feat: React Query 통합 및 관련 패키지 추가
  omechu-app/package.json
  omechu-app/src/app/layout.tsx
  omechu-app/src/app/lib/api/client.ts
  omechu-app/src/app/lib/providers/ReactQueryProvider.tsx
  omechu-app/yarn.lock
Labels: feat

#110 Feature/mainpage api #96
  omechu-app/public/image/food-sprite.svg
  omechu-app/public/image/loading-bg.svg
  omechu-app/src/app/components/common/MenuInfoCard.tsx
  omechu-app/src/app/components/mainpage/MainLoading.tsx
  omechu-app/src/app/components/mainpage/MealIngredientButton.tsx
  omechu-app/src/app/components/mainpage/MealStyleButton.tsx
  omechu-app/src/app/components/mainpage/MealTypeButton.tsx
  omechu-app/src/app/constant/mainpage/Option.ts
  omechu-app/src/app/constant/mainpage/RestaurantData.ts
  omechu-app/src/app/constant/mainpage/resultData.ts
  omechu-app/src/app/fullmenu/menu-detail/page.tsx
  omechu-app/src/app/layout.tsx
  omechu-app/src/app/lib/stores/locationAnswer.store.ts
  omechu-app/src/app/lib/stores/questionAnswer.store.ts
  omechu-app/src/app/lib/stores/tagData.store.ts
  omechu-app/src/app/mainpage/api/api.ts
  omechu-app/src/app/mainpage/components/BudgetStep.tsx
  omechu-app/src/app/mainpage/components/FinalChoiceStep.tsx
  omechu-app/src/app/mainpage/components/FoodCardEx.tsx
  omechu-app/src/app/mainpage/components/LocationModal.tsx
  omechu-app/src/app/mainpage/components/MealTimeStep.tsx
  omechu-app/src/app/mainpage/components/MoodStep.tsx
  omechu-app/src/app/mainpage/components/PurposeStep.tsx
  omechu-app/src/app/mainpage/components/TagCard.tsx
  omechu-app/src/app/mainpage/components/WhoStep.tsx
  omechu-app/src/app/mainpage/example_testpage/components/LoginPromptModal.tsx
  omechu-app/src/app/mainpage/example_testpage/components/LoginPromptModal2.tsx
  omechu-app/src/app/mainpage/hooks/useGetRecommendMenu.ts
  omechu-app/src/app/mainpage/hooks/useGetRestaurants.ts
  omechu-app/src/app/mainpage/location-answer/page.tsx
  omechu-app/src/app/mainpage/meal-answer/page.tsx
  omechu-app/src/app/mainpage/page.tsx
  omechu-app/src/app/mainpage/question-answer/[step]/page.tsx
  omechu-app/src/app/mainpage/result/[menuId]/page.tsx
  omechu-app/src/app/mainpage/result/page.tsx
  omechu-app/src/app/mainpage/utils/handleLocation.ts
Labels: feat, refactor

#118 feat:/마이페이지/찜목록 api 수정-#116
  omechu-app/src/app/mypage/favorites/page.tsx
Labels: feat
